# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Secrets
      uses: google/secrets-sync-action@v1.4.1
      with:
        SECRETS: "DOCKER_PASSWORD"
        REPOSITORIES: |
          "https://github.com/princedeepak2012/Spring-Native.git"
        DRY_RUN: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONCURRENCY: 1
